### ISSUE TITLE
Return movie wrong logic.

### ISSUE THREAD

**Issue by pskrzypek84** [Jakub-Izbicki/Patronage-entry-task#8]
When I return movie with ID=1 and get available movies I got:

```
[
  {
    "id": 1,
    "title": "n0",
    "description": "desc",
    "type": "newest",
    "price": 15,
    "rentedBy": {
      "id": 12,
      "login": "user",
      "rentalWallet": 79,
      "role": "USER"
    },
    "available": true
  },
......
]
```

User should be removed from rentedBy section.

**Comment by Jakub-Izbicki** [comment]
I thought it doesnt matter that the rentedBy field is filled, because the avaliability of the movie still only depends on the "avaliable" field, and when searching for user's rented movies, the app searches for movies with avaliability = false and rentedBy = the selected user, so in this case the movie with id = 1 would show up as not rented. And when another user rents this movie the "rentedBy" field is overwritten. Still, I will change it so the field "rentedBy" field is cleared after the movie is returned, as you pointed out.

**Comment by pskrzypek84** [comment]
I undarstand that but, in general, resource should always returns correct data.
